let firstName = "neil";
let lastName = "tran";
let age = 31;
let dateOfBirth = "05/11/1988";
let address = "63 loyola bay";
console.log("first name : " +firstName );
console.log("last name : " +lastName );
console.log("age  : " +age );
console.log("date of birth : " +dateOfBirth );
console.log("address : " +address );