var firstName = "neil";
var lastName = "tran";
var age = 31;
var dateOfBirth = "05/11/1988";
var address = "63 loyola bay";
console.log("first name : " +firstName );
console.log("last name : " +lastName );
console.log("age  : " +age );
console.log("date of birth : " +dateOfBirth );
console.log("address : " +address );